#!/usr/bin/env python2

import cgi
import cgitb
cgitb.enable(display=0, logdir="/tmp/cloud.log")

print "Content-type: application/json"
print

import json

from libcloud.compute.providers import set_driver
from libcloud.compute.types import Provider
from libcloud.compute.providers import get_driver

set_driver('stratuslab', 'stratuslab.libcloud.compute_driver', 'StratusLabNodeDriver')
StratusLabDriver = get_driver('stratuslab')
driver = StratusLabDriver('default')

images = [(i.name, i.id) for i in driver.list_images()]

result = {
    "errors": [],
    "images": images,
}

print json.dumps(result)
